### ISSUE TITLE
Title Page - A4 - PDF

### ISSUE THREAD

**Issue by stephanebertrand** [ifrost/afterwriting-labs#102]
Problems with Contact and Copyright, not in the bottom of the page in A4 format.
So date and notes are override by the text. Ex :

Title: **BEST TITLE**
Credit: Writen By
Authors: Best Author
Date: Today
Notes:
    the complexity
    of 
    simplicity
Contact:
    mail@mail.com
    00 00 00 00 00 
Copyright: Best Author Compagny

**Comment by ifrost** [comment]
The provided example renders fine:

![aw-cp](https://user-images.githubusercontent.com/745532/95243000-454b6500-0810-11eb-8f51-803a86419a91.PNG)

Please note that "Authors" is not supported at the moment (use "Author" instead). The positioning of each item is predefined (notes and copyright info is on the left, date and contact info on the right).
