### ISSUE TITLE
INT. / EXT. Scene is different than EXT. Scene

### ISSUE THREAD

**Issue by comicsads** [ifrost/afterwriting-labs#115]
I'm not sure if this is intended behavior but having the two scene headings
`INT. / EXT. Jim's house`
`EXT. Jim's house`
Will give the two locations:
`/ EXT. JIM'S HOUSE`
`JIM'S HOUSE`

**Comment by ifrost** [comment]
Please use: `INT./EXT. LOCATION` (no spaces) or `INT/EXT LOCATION` (no dots and spaces) to get correct stats.
