### ISSUE TITLE
Google Drive login not working

### ISSUE THREAD

**Issue by SteeveBlack** [ifrost/afterwriting-labs#120]
Version: 1.12.6 (2019/12/03) afterwriting.com

Reproduction: Clicking "Open from Google Drive" and attempting signin, the following message is displayed by accounts.google.com:

"Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In."

**Comment by Gideon357** [comment]
I have this issue, but it authorizes and loads the file. When I close and re-open the site, the file won't load when I select it in Drive.

**Comment by ifrost** [comment]
Loading from Google Drive should be working now - the app has been approved by Google. After refreshing the page the content is not automatically loaded from Google Drive, though, and the file has to be opened again.

**Comment by Gideon357** [comment]
I understand that, but the file load is just not working now. It authorizes, but it doesn't load the file

**Comment by ifrost** [comment]
I'm not able to reproduce it :/  When you select the file again - does the popup with the list of files disappear? Are there any errors in the console / dev tools? Could you try doing it again in incognito mode?

**Comment by ifrost** [comment]
Loading files from Drive should be working now. If you're still experiencing problems please open a new issue with steps to reproduce and errors from the console/network tab.
