### ISSUE TITLE
{two spaces} support is missing

### ISSUE THREAD

**Issue by KennethKo** [ifrost/afterwriting-labs#140]
The app doesn't appear to translate `{two spaces}` to a blank space in the context of dialogue. Indeed, I don't see the string "`two spaces`" anywhere in the afterwriting-labs code repo.

It's in the current version of the fountain.io spec (1.1 2014-03-14) here: https://fountain.io/syntax#section-br

**Comment by ifrost** [comment]
It is supported. When you use two consecutive space characters (and nothing else in the same line) it will show up in the editor as a "non-breaking line":

![ts-editor](https://user-images.githubusercontent.com/745532/104844567-3d03cb00-58d1-11eb-88d1-f37d44907a39.png)

It will allow you to render the dialogue like this:

![ts-formatted](https://user-images.githubusercontent.com/745532/104844582-53118b80-58d1-11eb-9172-8c25e81f7be5.png)

If you didn't put two spaces it'd render like "Hit or stand sir" was an action block, not dialogue, i.e.:

![ts-formatted-2](https://user-images.githubusercontent.com/745532/104844600-6d4b6980-58d1-11eb-99fe-1bc0b5d15aa8.png)
