### ISSUE TITLE
Conversion is not compatible with Japanese/Chinese characters.

### ISSUE THREAD

**Issue by n-studio** [ifrost/afterwriting-labs#36]
Conversion from fountain to pdf is not compatible with Japanese/Chinese characters.
Characters are replaced by blank spaces. Is it related to the font? #25

**Comment by ifrost** [comment]
Sorry, Japanese/Chinese characters are not supported yet as the currently embedded font does not include them. Yes, it's related to #25, I'll consider also some other options like fallback to the default system font. Do you know about any specific formatting requirements for Japansese/Chinese scripts (e.g. different margins). Any idea how does the "1 page = 1 minute" rule apply for these scripts? Ideally I'd like to make statistics as accurate as possible

**Comment by n-studio** [comment]
Hi!
Sorry for the late reply, I'm not sure about the rule.
I have a 10 page English script that becomes 12 pages in Japanese and another 10 page English script that becomes 9 pages in Japanese.
Falling back to the default system font would be a great idea.

**Comment by ifrost** [comment]
Closing this, util non-standard formatting is supported. I couldn't find any good examples but it seems that Chinese scripts follow a different format (e.g. https://www.youtube.com/watch?v=_taWSzIaBYg)
