### ISSUE TITLE
Words are skipped during conversion to PDF

### ISSUE THREAD

**Issue by aphex10** [ifrost/afterwriting-labs#41]
In the following situation I've found that words are being skipped when you preview the PDF.

Type out "She slides her phone over and fumbles with her watch strap." (or copy/paste, I won't judge!)

With page size on "A4", the word "watch" is skipped when you preview in PDF. "US letter" doesn't have the same issue.

I'm using Firefox 47.0.

The bug happens for both the default firefox PDF viewer and the experimental JavaScript PDF viewer.

I've only noticed the bug on this particular line, so perhaps that sentence is the perfect storm of page width and word lengths?

Keep up the great work!

**Comment by ifrost** [comment]
Great spot! Thank you reporting this. I've just released the fix (v1.2.26). Should be working now!

**Comment by aphex10** [comment]
That did the trick. Thanks for the fix!
