### ISSUE TITLE
Feature request: config option underline_scene_headers

### ISSUE THREAD

**Issue by rnkn** [ifrost/afterwriting-labs#60]
It would be good to be able to underline scene headings.

I think Paul Thomas Anderson writes his scripts with underlined scene headings.

**Comment by ifrost** [comment]
I like it! I will add to the options. Thanks!

BTW. It's possible to achieve it now. Not very convenient, but... possible :)

```
._EXT. BRICK'S PATIO - DAY_

A gorgeous day.  The sun is shining.  But BRICK BRADDOCK, retired police detective, is sitting quietly, contemplating -- something.

```

"." forces heading formatting; then you can use underline to format the whole line.
