### ISSUE TITLE
Let's Encrypt (TLS/SSL) on afterwriting.com

### ISSUE THREAD

**Issue by crasm** [ifrost/afterwriting-labs#64]
Would you be able to add https to afterwriting.com?

Without https it might be possible for a malicious third-party on the network to gain access to the user's linked dropbox/google drive (or at least screenplay contents).

(Since the site is static, hosting it (with TLS) was easy enough: https://afterwriting.vczf.io. Dropbox and Google Drive don't work due to the different domain.)

**Comment by ifrost** [comment]
I added HTTPS to afterwriting.com

To use Dropbox/Google Drive on your own domain you will need to setup your an app with Dropbox/Google Drive allowing connection from your domain and update API keys in dropbox.js and googledrive.js

**Comment by crasm** [comment]
I'll look into the API keys.

For https, it's giving me a security warning:
```
afterwriting.com uses an invalid security certificate.

The certificate is only valid for the following names:
  *.github.com, github.com, *.github.io, github.io  
```

Are you using github pages?

**Comment by ifrost** [comment]
Yep, afterwriting is hosted on github-pages (https://ifrost.github.io/afterwriting-labs/)
