### ISSUE TITLE
npm package has CRLF (DOS) line endings

### ISSUE THREAD

**Issue by rnkn** [ifrost/afterwriting-labs#69]
Hey Piotr,

I just installed `afterwriting@1.3.7` from npm and ran into an old error:
~~~
env: node\r: No such file or directory
~~~
and opening `awc.js` shows DOS encoding with CRLF line endings. Replacing with LF and saving solves the issue.

I found what I think is the definitive fix for this:
https://github.com/npm/npm/issues/13203

In short, it is to configure git on Windows with `core.autocrlf = false`.

**Comment by ifrost** [comment]
Thanks, I'll update my config and re-publish the package.

**Comment by ifrost** [comment]
Try installing version 1.7.0. Should be working now!

**Comment by rnkn** [comment]
Looking good, thanks 👌
