### ISSUE TITLE
Indents Not Recognized in Action Lines for PDF Export

### ISSUE THREAD

**Issue by eWrekt** [ifrost/afterwriting-labs#95]
Hey folks,

In fountain, I can indent an action line with spaces and tabs that should carry over into the interpreted document; however, it seems the current PDF export does not support this feature. Is it possible to implement this?

Quote from [fountain.io:](https://fountain.io/syntax#section-action)

> Tabs and spaces are retained in Action elements, allowing writers to indent a line. Tabs are converted to four spaces.

Thank you!

source:  [https://fountain.io/syntax#section-action](https://fountain.io/syntax#section-action)

**Comment by ifrost** [comment]
Thanks for reporting this. I'll have a look at this.

**Comment by ifrost** [comment]
Should be okay now!
